{"uuid": "e364825d-f722-4935-8921-131b889b9b80", "children": ["ad872d63-d0dc-478c-9b27-a8cf431fa497", "b672e8db-532c-4bf5-8e9a-c270fb0d4044", "aede536e-1ef2-46b6-829c-83aa1221e6a9", "ccf9d9ac-e4c7-40e6-a8e6-d18aba51300f", "cdc326c3-423f-4dca-a100-9e8c1b0d6a05", "5334df5e-5236-4917-9170-ce127889bcbf", "04a526ff-86b3-469c-a320-c3a1e02b43ad", "73409f1e-fa2c-406e-8761-c097b601460b", "2395c681-70e1-492e-8fe4-199e3bd2357e"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=134.0.6998.36)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6C1ACFE45+26629]\n\t(No symbol) [0x00007FF6C1A36010]\n\t(No symbol) [0x00007FF6C18C931A]\n\t(No symbol) [0x00007FF6C18C5D10]\n\t(No symbol) [0x00007FF6C18B68C9]\n\t(No symbol) [0x00007FF6C18B8638]\n\t(No symbol) [0x00007FF6C18B6BD6]\n\t(No symbol) [0x00007FF6C18B6656]\n\t(No symbol) [0x00007FF6C18B631A]\n\t(No symbol) [0x00007FF6C18B3E9F]\n\t(No symbol) [0x00007FF6C18B478C]\n\t(No symbol) [0x00007FF6C18CD16A]\n\t(No symbol) [0x00007FF6C197102E]\n\t(No symbol) [0x00007FF6C1947AAA]\n\t(No symbol) [0x00007FF6C1970169]\n\t(No symbol) [0x00007FF6C1947883]\n\t(No symbol) [0x00007FF6C1910550]\n\t(No symbol) [0x00007FF6C1911803]\n\tGetHandleVerifier [0x00007FF6C1E272BD+3529853]\n\tGetHandleVerifier [0x00007FF6C1E3DA22+3621858]\n\tGetHandleVerifier [0x00007FF6C1E324D3+3575443]\n\tGetHandleVerifier [0x00007FF6C1B9B77A+860474]\n\t(No symbol) [0x00007FF6C1A4088F]\n\t(No symbol) [0x00007FF6C1A3CBC4]\n\t(No symbol) [0x00007FF6C1A3CD66]\n\t(No symbol) [0x00007FF6C1A2C2C9]\n\t(No symbol) [0x00007FF960E1E8D7]\n\tRtlUserThreadStart [0x00007FF96179BF6C+44]\n\n", "trace": "  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\tejas.vinerkar\\PycharmProjects\\POM_Framework\\tests\\test_randoim.py\", line 8, in setup\n    driver.get(\"https://yourwebsite.com\")  # Replace with actual URL\n  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\tejas.vinerkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742283290901, "stop": 1742283299695}], "start": 1742283290901, "stop": 1742283300398}